/*
 *
 *   Title of project :
 *   Date of creation :
 *   Author(s) : PierreLgol
 *   github : https://github.com/pierrelgol
 *
 *   More on the project :
 *
 *   #TODO(s) :
 *
 *
 */

//--------------------[     DEPENDENCIES DECLARATION     ]--------------------//

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>

//--------------------[     MAIN METHOD     ]--------------------------------//

/*7. Prime numbers can also be generated by an algorithm known as the Sieve
of Eratosthenes. The algorithm for this procedure is presented here. Write a
program that implements this algorithm. Have the program find all prime numbers
up to n = 150. What can you say about this algorithm as compared to the ones
used in the text for calculating prime numbers? Sieve of Eratosthenes Algorithm
To Display All Prime Numbers Between 1 and n

Step 1: Define an array of integers P. Set all elements Pi to 0, 2 <= i <= n.
Step 2: Set i to 2.
Step 3: If i > n,the algorithm terminates.
Step 4: If Pi is 0, then i is prime.
Step 5: For all positive integer values of j, such that i x j ≤ n, set Pixj
to 1. Step 6: Add 1 to i and go to step 3. */

#define SIZE 150

int main() {

  size_t i, j;
  u_int64_t P[SIZE] = {0};

  for( i = 2; i < SIZE; i++ ){
    
    for( j = i; ( i * j ) <= SIZE; j++ ){
      P[i*j] = 1;
    }
  }

  for ( i = 0; i < SIZE; i++ ){
    if(P[i] == 0) printf("%zu ",i);
  }

  return EXIT_SUCCESS;
}
